Repository FIAP-SA-Hermes-Foods/fiap-hf-src, pull requests merged in 2024-01, with the labels that each got.

#76 Improv/075
  Jenkinsfile
  infrastructure/kubernetes/deployment/app.yaml
  infrastructure/kubernetes/deployment/postgres.yaml
  infrastructure/kubernetes/deployment/swagger.yaml
  infrastructure/kubernetes/hpa/app.yaml
  infrastructure/kubernetes/hpa/postgres.yaml
  infrastructure/kubernetes/hpa/swagger.yaml
Labels: improvements

#78 Feat/077
  cmd/server/main.go
  docs/postman_collection/v1_hermes-foods.postman_collection.json
  docs/postman_collection/v2_hermes-foods.postman_collection.json
  docs/project_structure.md
  internal/adapters/driven/http/api-mercadoPago/api.go
  internal/adapters/driven/http/api-mercadoPago/api_test.go
  internal/adapters/driven/http/api-mercadoPago/coverage.sh
  internal/adapters/driven/http/api-mercadoPago/mock.go
  internal/adapters/driver/repository/client/clientRepository.go
  internal/adapters/driver/repository/client/clientRepository_test.go
  internal/adapters/driver/repository/client/coverage.sh
  internal/adapters/driver/repository/client/mock.go
  internal/adapters/driver/repository/order/coverage.sh
  internal/adapters/driver/repository/order/mock.go
  internal/adapters/driver/repository/order/orderRepository.go
  internal/adapters/driver/repository/order/orderRepository_test.go
  internal/adapters/driver/repository/order_product/coverage.sh
  internal/adapters/driver/repository/order_product/mock.go
  internal/adapters/driver/repository/order_product/order_product.go
  internal/adapters/driver/repository/order_product/order_product_test.go
  internal/adapters/driver/repository/product/coverage.sh
  internal/adapters/driver/repository/product/mock.go
  internal/adapters/driver/repository/product/productRepository.go
  internal/adapters/driver/repository/product/productRepository_test.go
  internal/adapters/driver/repository/voucher/coverage.sh
  internal/adapters/driver/repository/voucher/mock.go
  internal/adapters/driver/repository/voucher/voucherRepository.go
  internal/adapters/driver/repository/voucher/voucherRepository_test.go
  internal/handler/web/client.go
  internal/handler/web/health.go
  internal/handler/web/middleware.go
  internal/handler/web/order.go
  internal/handler/web/product.go
  internal/handler/web/voucher.go
  internal/handler/web/web.go
Labels: feature, improvements

#81 bugfix/080
  internal/adapters/driver/repository/client/clientRepository.go
  internal/adapters/driver/repository/order/orderRepository.go
  internal/adapters/driver/repository/order_product/order_product.go
  internal/adapters/driver/repository/product/productRepository.go
  internal/adapters/driver/repository/voucher/voucherRepository.go
  internal/handler/web/client.go
  internal/handler/web/middleware.go
  internal/handler/web/middleware_test.go
  internal/handler/web/order.go
  internal/handler/web/product.go
  internal/handler/web/voucher.go
  internal/handler/web/web.go
Labels: bug

#84 Improv/082
  cmd/server/main.go
  infrastructure/db/DML/001_init_db.sql
  infrastructure/db/DML/002_populate_tables.sql
  internal/core/application/application.go
  internal/core/entity/common/category.go
  internal/core/entity/common/expires_at.go
  internal/core/service/client_test.go
  internal/core/service/order.go
  internal/core/service/order_product_test.go
  internal/core/service/order_test.go
  internal/core/service/product.go
  internal/core/service/product_test.go
  internal/core/service/voucher.go
  internal/core/service/voucher_test.go
  internal/gateways/http/api-mercadoPago/api.go
  internal/gateways/http/api-mercadoPago/api_test.go
  internal/gateways/http/api-mercadoPago/coverage.sh
  internal/gateways/http/api-mercadoPago/mock.go
  internal/gateways/repository/client/clientRepository.go
  internal/gateways/repository/client/clientRepository_test.go
  internal/gateways/repository/client/coverage.sh
  internal/gateways/repository/client/mock.go
  internal/gateways/repository/order/coverage.sh
  internal/gateways/repository/order/mock.go
  internal/gateways/repository/order/orderRepository.go
  internal/gateways/repository/order/orderRepository_test.go
  internal/gateways/repository/order_product/coverage.sh
  internal/gateways/repository/order_product/mock.go
  internal/gateways/repository/order_product/order_product.go
  internal/gateways/repository/order_product/order_product_test.go
  internal/gateways/repository/product/coverage.sh
  internal/gateways/repository/product/mock.go
  internal/gateways/repository/product/productRepository.go
  internal/gateways/repository/product/productRepository_test.go
  internal/gateways/repository/voucher/coverage.sh
  internal/gateways/repository/voucher/mock.go
  internal/gateways/repository/voucher/voucherRepository.go
  internal/gateways/repository/voucher/voucherRepository_test.go
  internal/handler/web/client.go
  internal/handler/web/middleware.go
  internal/handler/web/middleware_test.go
  internal/handler/web/order.go
  internal/handler/web/product.go
  internal/handler/web/voucher.go
  internal/handler/web/web.go
  internal/handler/web/web_test.go
  pkg/migration/migration.go
  pkg/postgres/postgres.go
Labels: improvements
